### PR TITLE
Pin sundials 2.7

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@jakirkham I've got a problem with this package: I just pinned sundials in assimulo as the recent sundials update to 3.0 is not compatible, but now when I install assimulo the newest revision is ignored and sundials is let free to latest 3.0. I thought the newest version of assimulo would downgrade sundials unfortunately it's the other way around. How can I solve this ? Could the old assimulo packages be removed ?

**Comment by ocefpaf** [comment]
What version and build number of `assimulo` needs to be removed?

**Comment by jschueller** [comment]
@ocefpaf Basically all builds except the latest with build number 5.

**Comment by ocefpaf** [comment]
Please take a look at https://anaconda.org/conda-forge/assimulo/files and see if everything is OK.

**Comment by jschueller** [comment]
Maybe older builds must be marked as broken too: only page 1 of 3 is done.

**Comment by ocefpaf** [comment]
Should be OK now. Can you check again?

**Comment by jschueller** [comment]
Thanks!

**Comment by jschueller** [comment]
Is it the only way to deal with such problems?

**Comment by ocefpaf** [comment]
> Is it the only way to deal with such problems?

Fix the conda solver to interpret build numbers as build numbers :stuck_out_tongue_winking_eye:

**Pull request merged**
